apiVersion: argoproj.io/v1alpha1
kind: Application
metadat:
  name: myapp-argo-Application
  namespace:  argocd
spec:
  project: default

source:
  repoURL:  https://github.com/Alirazaops/Kubernetes.git
  targetRevision: main
  path: Services-ClusterIP-NodePort-LoadBalancer
destination:
  server: https://kubernetes.default.svc
  namespace:  myapp
  
syncPolicy:
  syncOptions:
  - CreateNamespace=true

  automated:
    selfHeal: true
    prune:  true