apiVersion: apps/v1
kind: ReplicaSet
Metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLables:
      app:  nginx
  template:
    metadata:
      lables:
        app:  nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            -container: 80